include = [ "**/*.toml" ]

[formatting]
	align_entries         = true
	align_comments        = true
	array_trailing_comma  = true
	array_auto_expand     = true
	array_auto_collapse   = true
	compact_arrays        = false
	compact_inline_tables = false
	inline_table_expand   = true
	compact_entries       = false
	column_width          = 100
	indent_tables         = true
	indent_entries        = true
	indent_string         = "\t"
	trailing_newline      = true
	reorder_keys          = false
	reorder_arrays        = false
	reorder_inline_tables = false
	allowed_blank_lines   = 2
	crlf                  = false
